version: "3.9"

services:
  backend:
    build:
      context: ./backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 7000:3000
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate:v4.16.2
    volumes:
      - ./backend/migrations:/migrations
  administradores:
    build:
      context: ./administradores
    depends_on:
      - backend
    restart: always
    env_file:
      - .env
    ports:
      - 7001:3000

volumes:
  postgres-data:
