version: "3.9"

services:
  backend:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8080:3000
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
