version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - CONNECTION_STRING=user=rutadestino password=password dbname=rutadestino sslmode=disable host=db
    ports:
      - 8080:3000
    volumes:
      - ./:/app
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=rutadestino
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgres/data

volumes:
  postgres-data:
