version: "3.9"

services:
  backend:
    image: cosmtrek/air:v1.49.0
    working_dir: /app
    env_file:
      - .env
    ports:
      - 8080:3000
    volumes:
      - ./backend:/app
    entrypoint:
      [
        "/go/bin/air",
        "--build.cmd",
        "go build -buildvcs=false -o ./tmp/main ."
      ]
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate:v4.16.2
    volumes:
      - ./backend/migrations:/migrations

volumes:
  postgres-data:
